# https://docs.github.com/en/actions/guides
# CI name , it will display on github's action page menu
name: Execute commands
# trigger on which this CI should be run
on: # push operation is operate
  push:
    # here since my repository branch is named `main` , you should follow your own repository like `master`
    branches: [main]
# CI enviroment settings
env:
  STATE_RELEASE_VERSION: "1.0" # version
  
jobs:
  build:
    name: 执行Linux指令
    runs-on: ubuntu-latest # use latest ubuntu to run the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Show files
        run: ls -a
      - name: grep
        run: python -u grep.py
      - name: find
        run: python -u find.py